# SPDX-License-Identifier: AGPL-3.0-only
# 著作權所有 (C) 2026 TW0hank0
#
# 本檔案屬於 positive_toolbox 專案的一部分。
# 專案儲存庫：https://github.com/TW0hank0/positive_toolbox
#
# 本程式為自由軟體：您可以根據自由軟體基金會發佈的 GNU Affero 通用公共授權條款
# 第 3 版（僅此版本）重新發佈及/或修改本程式。
#
# 本程式的發佈是希望它能發揮功用，但不提供任何擔保；
# 甚至沒有隱含的適銷性或特定目的適用性擔保。詳見 GNU Affero 通用公共授權條款。
#
# 您應該已經收到一份 GNU Affero 通用公共授權條款副本。
# 如果沒有，請參見 <https://www.gnu.org/licenses/>。

name: commit-check

on:
  push:
    paths-ignore:
      - "README.md"
      - "READMEs/**"
      - ".vscode/**"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # - name: install rustup (Windows)
      #   if: runner.os == 'Windows'
      #   shell: pwsh
      #   run: |
      #     Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
      #     ls
      #     .\rustup-init.exe -y --profile minimal

      # - name: install rustup (Linux)
      #   if: runner.os == 'Linux'
      #   run: |
      #     curl https://sh.rustup.rs -o rustup-init.sh
      #     sh rust-initup.sh -y

      # - name: check Install
      #   run: |
      #     rustc --version
      #     cargo --version

      # - name: install cargo-about
      #   run: |
      #     cargo install cargo-about

      # - name: check cargo-about install
      #   run: |
      #     cargo-about --version

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: check uv install
        run: |
          uv self version

      - name: Install Go (Required for addlicense)
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install addlicense
        run: go install github.com/google/addlicense@latest

      - name: install tool
        run: |
          uv venv
          uv pip install pip-licenses licensecheck

      - name: run PLT
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          uv run main.py .
